import { z } from 'zod';

export const EnkelvoudigInformatieObjectSchema = z.object({
  url: z.string().url(),
  bronorganisatie: z.string().max(9),
  creatiedatum: z.string(),
  titel: z.string().max(200),
  auteur: z.string().max(200),
  taal: z.string().length(3),
  versie: z.number(),
  beginRegistratie: z.string().datetime(),
  informatieobjecttype: z.string().max(200),
  locked: z.boolean(),
  bestandsdelen: z.array(
    z.object({
      url: z.string(),
      volgnummer: z.number(),
      omvang: z.number(),
      voltooid: z.boolean(),
      lock: z.string(),
    }),
  ),
  formaat: z.string().max(255).optional(),
  vertrouwelijkheidaanduiding: z.enum([
    'openbaar',
    'beperkt_openbaar',
    'intern',
    'zaakvertrouwelijk',
    'vertrouwelijk',
    'confidentieel',
    'geheim',
    'zeer_geheim',
  ]).optional(),
  status: z.enum([
    'in_bewerking',
    'ter_vaststelling',
    'definitief',
    'definitief',
    'gearchiveerd',
  ]).optional(),
  bestandsnaam: z.string().optional(),
  inhoud: z.string().optional(),
  bestandsomvang: z.number().optional(),
  link: z.string().url().max(200).optional(),
  beschrijving: z.string().max(1000).optional(),
  verzenddatum: z.coerce.date().optional(),
  verschijningsvorm: z.string().optional(),
  trefwoorden: z.array(z.string()).optional(),
});
export type EnkelvoudigInformatieObject = z.infer<typeof EnkelvoudigInformatieObjectSchema>;
